import Config

# Configure your database
config :niko_safe, NikoSafe.Repo,
  username: "postgres",
  password: System.get_env("POSTGRES"),
  hostname: "localhost",
  database: "niko_safe_dev",
  stacktrace: true,
  port: "5432",
  # ssl: true,
  #  ssl_opts: [verify: :verify_peer, cacertfile: :public_key.cacerts_get()],
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# configuration of africastlking credentialks
config :at_sandbox,
  api_key: System.get_env("ATLIVE")

# here am configuring africastalking api for this projects
config :at_ex,
  api_key: System.get_env("ATSANBOX"),
  username: "sandbox",
  # When changed to "false" one will use the live endpoint url
  sandbox: true,
  # Add your specific product name.
  stk_product_name: "AtEx",
  b2c_product_name: "AtEx",
  b2b_product_name: "AtEx",
  bank_checkout_product_name: "AtEx",
  bank_transfer_product_name: "AtEx",
  card_checkout_product_name: "AtEx"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :niko_safe, NikoSafeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 5000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "201TivDQTSkmdZX/eMo58//WjLlBwhOeh/9Hh06sRqrBY1fmkeoCmm7Qm501aVPd",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:niko_safe, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:niko_safe, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :niko_safe, NikoSafeWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/niko_safe_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :niko_safe, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
